version: '3'
services:
  loc_counter_badge:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    ports:
    - 5000:80
    volumes:
      - type: bind
        source: ./conf.d/config.cfg
        target: /app/conf.d/config.cfg